### ISSUE TITLE
ouput grids for country

### ISSUE THREAD

**Issue by nokout** [mapcode-foundation/mapcode-python#1]
Hi, I'm looking at the feasibility of using mapcodes as a basis for aggregation of spatial data - essentially to use it as a low level grid. 

One of the things I am interested in is generating that grid as a set of polygons for each mapcode in Australia. I'm not familiar with the API yet and am not looking forward to understanding the underlying C++ code, so I was wondering if there is an existing function that I can use or a known starting lat/lon and degree/distance offsets that I could use to achieve this?

Any help appreciated.

Cheers, Nigel

**Comment by rijnb** [comment]
No, the Python or C/C++ API does not expose that information off-the-shelf. You should be able to generate from the provided data, but that indeed requires diving into the source code. The Java library may be easier as a starting place, in that case.
